import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print("Original numbers:")
print(x)
print(y)
print("Comparision greater:")
print(np.greater(x,y))
print("Comparission greater equal")
print(np.greater_equal(x,y))
print("Comparisson less")
print(np.less(x,y))
print("Comparisson less equal")
print(np.less_equal(x,y))
