li=[1,2,'a',7,"apple"]
li.insert(2,"orange")
print("The string 'orange' is inserted to the third position.The list:\n ")
print(li,"\n")
li.remove(1)
print("The element '1' is removed from the list.The list:\n")
print(li,"\n")
li.append("banana")
print("The element 'banana' is appended onto the list.The list:\n")
print(li)
print("The length of the list: ",len(li))
element=li.pop()
print("\nThe popped element is:",element,"\n")
print(li,"\n")
li.clear()
print("\nAll elements cleared  from  the list.\n")
print(li)
